# Generated by Django 4.2.28 on 2026-02-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_selected_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_seats',
            field=models.TextField(blank=True),
        ),
    ]
