# Generated by Django 4.2.28 on 2026-02-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_to', to='locations.city')),
                ('source_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_from', to='locations.city')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
